version: "3.5"
networks:
    mimir-api-test-network:
        name: mimir-api-test-network
services:
    db-mysql-test:
        container_name: mimir-api-test-db
        image: mysql:latest
        command: --init-file /usr/src/app/init.sql
        volumes:
            - ./mysql/init.sql:/usr/src/app/init.sql
            - ./volumes/db:/var/lib/mysql
        expose:
            - "3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: <PASSWORD>
            MYSQL_DATABASE: <DATABASE_NAME>
            MYSQL_USER: <USER>
            MYSQL_PASSWORD: <PASSWORD>
        networks:
            - mimir-api-test-network

    mimir-api-test:
        container_name: mimir-api-test
        build:
            context: ./api
            dockerfile: Dockerfile.test
        image: treed1104/mimir-api-test:latest
        restart: always
        links:
            - db-mysql
        ports:
            - "5000:5000"
        networks:
            - mimir-api-test-network
